### ISSUE TITLE
How to access session id?

### ISSUE THREAD

**Issue by mohsen1** [browserstack/webdriverio-browserstack#8]
Is there anyway to access the session ID via the JS API?

**Comment by huoxito** [comment]
been looking for this too @mohsen1 in case it helps anyone, you can grab the current session id with `browser.url().sessionId`

**Comment by matisnape** [comment]
@huoxito you can get it with just `browser.sessionId` :)

**Comment by imhighyat** [comment]
It is telling me browser is not defined. I used both browser.sessionId and browser.url().sessionId

**Comment by maddysk3** [comment]
@imhighyat use below mentioned code:
--------------------------------------------------
driver.session_.then(function(sessionData) {
    console.log(sessionData.id_);
});
--------------------------------------------------
